version: '2'
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./data:/var/project/data
            - ./navigate:/var/project/navigate
        depends_on:
            - redis
        command: tail -f /dev/null
    redis:
        image: redis